language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-add-repository -y ppa:smspillaz/cmake-2.8.12
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qtbase5-dev cmake

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON ..

script:
  - make && ctest
