sudo: required
dist: trusty

language: c++

compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt592-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt592base

before_script:
  - export PATH=$PATH:/opt/qt592/bin

script:
  - cmake -DBUILD_TESTS=on .
  - make
  - ctest
