name: Compile and Generate Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Install Additional Software
      run: |
        sudo apt install doxygen graphviz
    - name: Configure
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -E make_directory build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-Werror -Wall -Wextra'
    - name: Compile
      run: |
        cd build
        make
